# Server configuration file for cc-proxy
# Copy this file to ~/.cc-proxy/config.yaml and modify as needed
# This is the main server configuration (different from user.yaml which contains dynamic user settings)

# Configuration version
version: "1"

# Server settings
host: !env [CC_PROXY_HOST, "127.0.0.1"]  # Server bind address (uses env var or default)
port: !env [CC_PROXY_PORT, 8000]          # Server port (uses env var or default 8000)

# Development mode - enables debug features and verbose logging
dev: !env [CC_PROXY_DEV, false]

# CORS (Cross-Origin Resource Sharing) settings
# List of allowed origins for browser requests
cors_allow_origins:
  - "http://localhost:8000"
  - "https://yourdomain.com"

# Request/Response Dumping - for debugging and development
# Each toggle controls both original and transformed data (pre/post transformer processing)
# Files are numbered chronologically: 1_original, 2_transformed, 3_original, etc.
dump_headers: false     # Dump both original and transformed HTTP headers
dump_requests: false   # Dump both original and transformed request payloads  
dump_responses: false # Dump both pre-transformed and final response data
dump_dir: !env [CC_PROXY_DUMP_DIR, "~/.cc-proxy/dumps"] # Directory to save dump files

# Headers to redact in dumps for security
redact_headers:
  - authorization    # Bearer tokens, API keys
  - x-api-key       # API key headers  
  - cookie          # Session cookies
  - set-cookie      # Response cookies

# Fallback provider configuration
# Used when no user configuration is available or as emergency backup
fallback_api_url: !env [CC_PROXY_FALLBACK_URL, "https://api.anthropic.com"]  # Default to Anthropic API base URL
fallback_api_key: !env [CC_PROXY_FALLBACK_API_KEY, null]                                  # Required: Set your fallback API key

# Logging configuration
logging:
  level: !env [CC_PROXY_LOG_LEVEL, "INFO"]                    # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_enabled: !env [CC_PROXY_LOG_CONSOLE, true]          # Enable console (stdout) logging
  file_enabled: !env [CC_PROXY_LOG_FILE, true]                # Enable file logging
  log_file_dir: !env [CC_PROXY_LOG_DIR, ""]                   # Log directory (empty = ~/.cc-proxy/logs/)
  max_file_size: !env [CC_PROXY_LOG_MAX_SIZE, "10MB"]         # Maximum size before log rotation
  backup_count: !env [CC_PROXY_LOG_BACKUP_COUNT, 4]           # Number of backup files to keep
  rotation_when: !env [CC_PROXY_LOG_ROTATION, "midnight"]     # Rotation schedule: midnight, hourly, daily, weekly
