# Example configuration file for cc-proxy
# Copy this file to ~/.cc-proxy/config.yaml and modify as needed

# CORS settings
cors_allow_origins:
  - "http://localhost:8000"
  - "https://yourdomain.com"

# Server settings
host: "127.0.0.1"
port: 8000

# Development mode
dev: false

# Dump settings
dump_requests: false
dump_responses: false
dump_headers: false
dump_dir: "~/.cc-proxy/dumps"
redact_headers:
  - authorization
  - x-api-key
  - cookie
  - set-cookie

fallback_api_url: null
fallback_api_key: null

# Logging configuration
logging:
  level: "INFO" # (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  console_enabled: true
  file_enabled: true
  log_file_dir: ''  # defaults to ~/.cc-proxy/logs/
  max_file_size: "10MB"
  backup_count: 5
  rotation_when: "midnight"